<script lang="ts" setup>
import { EllipsisText } from '@vben/common-ui';

const text = `
Vben Admin is a backend solution based on Vue3.0, Vite, and TypeScript. It aims to provide out-of-the-box solutions for the development of medium and large projects. Including secondary encapsulation components, utils, hooks, dynamic menus, permission verification, multi-theme configuration, button-level permission control and other functions. The project will use the latest front-end technology stack, which can be used as a startup template for the project to help you quickly build enterprise-level middle and back-end product prototypes. It can also be used as an example to learn mainstream technologies such as vue3, vite, ts, etc. The project will continue to keep up with the latest technologies and apply them in projects. Vben Admin is a backend solution based on Vue3.0, Vite, and TypeScript. It aims to provide out-of-the-box solutions for the development of medium and large projects. Including secondary encapsulation components, utils, hooks, dynamic menus, permission verification, multi-theme configuration, button-level permission control and other functions. The project will use the latest front-end technology stack, which can be used as a startup template for the project to help you quickly build enterprise-level middle and back-end product prototypes. It can also be used as an example to learn mainstream technologies such as vue3, vite, ts, etc. The project will continue to keep up with the latest technologies and apply them in projects. Vben Admin is a backend solution based on Vue3.0, Vite, and TypeScript. It aims to provide out-of-the-box solutions for the development of medium and large projects. Including secondary encapsulation components, utils, hooks, dynamic menus, permission verification, multi-theme configuration, button-level permission control and other functions. The project will use the latest technology stack on the front end, which can be used as a startup template for the project to help you quickly build enterprise-level middle and back-end product prototypes. It can also be used as an example to learn mainstream technologies such as vue3, vite, ts, etc. The project will continue to keep up with the latest technologies and apply them in projects. Vben Admin is a backend solution based on Vue3.0, Vite, and TypeScript. It aims to provide out-of-the-box solutions for the development of medium and large projects. Including secondary encapsulation components, utils, hooks, dynamic menus, permission verification, multi-theme configuration, button-level permission control and other functions. The project will use the latest technology stack on the front end, which can be used as a startup template for the project to help you quickly build enterprise-level middle and back-end product prototypes. It can also be used as an example to learn mainstream technologies such as vue3, vite, ts, etc. The project will continue to keep up with the latest technologies and apply them in projects.
`;
</script>
<template>
  <EllipsisText :line="3" expand>{{ text }}</EllipsisText>
</template>
